### ISSUE TITLE
Configuring point opacity for scatter and bubble charts

### ISSUE THREAD

**Issue by ECrownofFire** [naver/billboard.js#1338]
## Description
The opacity for scatter and bubble charts [is hardcoded](https://github.com/naver/billboard.js/blob/649553ef352606af73afcaf35b364ce6b8f6c9cd/src/internals/ChartInternal.js#L977-L978), it'd be nice for that to be configurable.

**Comment by netil** [comment]
@ECrownofFire, you can control the opacity of `<circle>` elements doing this:

```css
.bb-circles circle {
    opacity: 1 !important;
}
```
