### ISSUE TITLE
Can't apply fill color to donut arc

### ISSUE THREAD

**Issue by alanorth** [naver/billboard.js#1777]
## Description
I'm trying to style a donut chart using CSS with Billboard.js v2.1.4 (I can't do it via the JavaScript API because the frontend code is separated from the backend build process where the styles get compiled). I've tried to set `fill` on the arc paths, but it doesn't seem to get applied. For some reason the `stroke` _does_ get applied.

## Steps to check or reproduce
JavaScript:

```js
bb.generate({
  bindto: "#chart",
  data: {
    columns: [
      ["data1", 30],
      ["data2", 130]
    ],
    type: "donut"
  }
});
```

CSS:

```css
.bb-arcs-data1 path {
  fill: red;
  stroke: red;
}

.bb-arcs-data2 path {
  fill: green;
  stroke: green;
}
```

Here's a JSFiddle to reproduce: https://jsfiddle.net/cn6k39j4/2/

Thank you in advance for any help.

**Comment by netil** [comment]
Hi @alanorth, for dataseries colors there's [`data.colors`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data%25E2%2580%25A4colors) options.

```js
bb.generate({
  bindto: "#chart",
  data: {
    columns: [
      ["data1", 30],
      ["data2", 130]
    ],
    type: "donut",
    colors: {
    	data1: "red",
        data2: "green"
    }
  }
});
```

Is highly recommended using the option provided, but if you need in somehow change colors via css, 
you can do by adding `!important` after each css property to prioritize applying it.

```css
.bb-arcs-data1 path {
  fill: red !important;
  stroke: red;
}
```
