### ISSUE TITLE
Cursor as pointer on click event

### ISSUE THREAD

**Issue by Rohit-Parte** [naver/billboard.js#220]
Hi @netil,

How to set cursor as a pointer on click event of bar chart.

**Comment by netil** [comment]
Try this.
```css
    .bb-event-rects .bb-event-rect {
         cursor: pointer;
    }
```
