### ISSUE TITLE
Close gap between bars

### ISSUE THREAD

**Issue by rtmalone** [naver/billboard.js#283]
Is there a way I am overlooking to decrease the space between bars on a bar chart? I know how to set width of the bar, but I need them closer together. C3.js used to have `bar.space`, but I don't think it has survived to the current version. Wouldn't help me anyway since I need D3 v4 support.

Thanks.

**Comment by netil** [comment]
@rtmalone, billboard.js was forked from C3.js 0.4.11 and `bar.space` was added from 0.4.17.
But, adding gap space between bars aren't difficult. Just set translateX CSS property for that.

```css
// Adjust the gap px if you need.
.bb-chart-bar:nth-child(odd){transform:translateX(-3px)}
.bb-chart-bar:nth-child(even){transform:translateX(3px)}
```
Left is before the CSS, and the right is afterh the above CSS.
![image](https://user-images.githubusercontent.com/2178435/36085069-51cacca8-1006-11e8-8da5-d02f675c0624.png)
