### ISSUE TITLE
[bug] region color styling broken in v3.10

### ISSUE THREAD

**Issue by ebencollins** [naver/billboard.js#3611]
## Description
Regions created with "class" property no longer have their fill color since v3.10. 

This seems to have happened in 0496ec6.

**Expected (v3.9.4)**
![](https://i.imgur.com/C7rkrGD.png)

**Actual (v3.10.3)**
![](https://i.imgur.com/ceLmKGK.png)

## Steps to check or reproduce
1. Add regions with class
2. Specify style with fill color for class
3. Observe region is still of default color

v3.10.3 (broken): https://stackblitz.com/edit/nisjec-buk5d2?file=index.ts
v3.9.4 (working): https://stackblitz.com/edit/nisjec-j5fxtt?file=index.ts

**Comment by netil** [comment]
hi @ebencollins, thanks for the report.
It a side-effect of #3323, which updated region's rect element default css rule.

**Comment by netil** [comment]
@ebencollins for workaround w/o library udpate, specify `rect` in each selector to increase the specifity.
(this will work after the fix also)

```css
  #styleForRegion .bb-region-0 rect {
    fill: red;
  }
  #styleForRegion .bb-region.foo rect {
    fill: green;
  }
```
