### ISSUE TITLE
How to put several graphs "gauge" on the same webpage

### ISSUE THREAD

**Issue by Phil353556** [naver/billboard.js#3942]
Hello,

How to have several "gauge" graph on a row and not one behind the previous ?
Thanks for any idea
Phil

![Image](https://github.com/user-attachments/assets/4c96ddfb-fc28-4837-956a-3e99eff18416)

**Comment by Phil353556** [comment]
hi,
I saw class=bb , may be  it is needed to overwrite but how to do that in a good way?

![Image](https://github.com/user-attachments/assets/e9e93ce2-9477-46d4-8145-c50d8ef2fc40)

Thanks
Phil

**Comment by netil** [comment]
Hi @Phil353556, you can override or re-style default css.
Don't know exactly what want to achieve, but made a simple example might help.
- https://jsfiddle.net/netil/by1m5fu0/

**Comment by Phil353556** [comment]
Hi,
What I should like to have is :   all the four gauges on a same line or row.
Something like this:
![Image](https://github.com/user-attachments/assets/b91f4f72-7e66-4c61-a2ef-2fb2da895f00)

I didn't see what should be overiden to achieve this result. 
Thank you so much for your help
Phil

**Comment by netil** [comment]
@Phil353556 well in that case, is not about chart functionality. Is about positioning elements.
There're several ways to do that, but simple ways is

```css
.bb {
   width: 150px;  /* set the width you need */
   float: left;
}
```
Checkout working example:
- https://jsfiddle.net/627dfr90/2/

**Comment by Phil353556** [comment]
thanks,
but in this case <center>   </center> before the div doesn't center the gauges on the webpage.

**Comment by netil** [comment]
well, in that case add some container element
- https://jsfiddle.net/netil/eb3Lqdth/3/

<img width="522" alt="Image" src="https://github.com/user-attachments/assets/da270946-ddaa-4d3c-a5b7-22a4e76bae53" />

```css
.container {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
}

.bb {
   width: 150px;
}
```
