### ISSUE TITLE
Question: Titles make me crazy / sorry

### ISSUE THREAD

**Issue by Phil353556** [naver/billboard.js#3964]
Hello,

I tried without success,  I didn't success to have several graphics on a single webpage with a title in bold for each. What I'm missing? 

Is there a specific order  to include 
.bb-title tspan:first-child { font-size: 17px; font-weight: bold; }

is it correct to put   tspan:first-child or is it another parameter ?

[testtitle.html.txt](https://github.com/user-attachments/files/19235731/testtitle.html.txt)

Thanks
Phil

**Comment by Phil353556** [comment]
FYI. I noticed on the webpage https://d3js.org/d3.v6.min.js  however the v7 is available: https://d3js.org/d3.v7.min.js
![Image](https://github.com/user-attachments/assets/1f9417c1-d506-4923-9387-18b5a1219ec6)


The goal, is to have on a same webpage several graphics (type lines and type gauge) with the first line of the title in 17px and bold and the second line if any in 14px not bold
I found the 17px is not there and overridden by 14px.
see screenshots
![Image](https://github.com/user-attachments/assets/21935c01-c026-486a-a0ec-fbf6ba1108a6)
![Image](https://github.com/user-attachments/assets/c2093077-ba55-4be1-b9d3-c2c2c9e2c7b8)

After several tries, I detect that adding a second line to each title for each graphic solve the problem.
[othertest.html.txt](https://github.com/user-attachments/files/19245825/othertest.html.txt)
[othertest_with_secondline.html.txt](https://github.com/user-attachments/files/19245826/othertest_with_secondline.html.txt)


I will be happy to read you @netil 
Best regards
Phil

**Comment by netil** [comment]
You need to deal with some css styling and specify correct css selector for this.
> first line of the title in 17px and bold and the second line if any in 14px not bold

@Phil353556. do

```css
/* style for the first line of title */
.bb-title tspan:first-child {
    font-size: 17px;
    font-weight: bold;
}

/* style for the second line of title */
.bb-title tspan:nth-child(2) {
    font-size: 14px;
}
```
