### ISSUE TITLE
Is there a y-axis rotation option?

### ISSUE THREAD

**Issue by drt0927** [naver/billboard.js#916]
## Description

![image](https://user-images.githubusercontent.com/14919000/58769732-ca06ed00-85e4-11e9-9f30-410f2b273cf2.png)

**Comment by netil** [comment]
Hi @drt0927, there's no option for that, but you can handle via css.

```css
.bb-axis-y-label {
	transform:rotate(0) translateX(50px);
}
```
